services:
  - name: flask-backend
    type: web
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    branch: main
    autoDeployTrigger: commit
#    buildCommand: pip install -r requirements.txt
#    startCommand: gunicorn Flask_Backend_Test:app
#    repo: https://github.com/Eidos-bot/Public_Website_Project

    dockerCommand: gunicorn Flask_Backend_Test:app
    region: ohio
    healthCheckPath: "/"
    envVars:
      - key: PORT
        value: "10000"

